/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Asus
 */
public class printreceipt extends javax.swing.JFrame {

    /**
     * Creates new form printreceipt
     */
    public printreceipt() {
        initComponents();
        getRecords();
        Container c=getContentPane();
        c.setBackground(new Color(0,51,51));
    }
    
    public void getRecords(){
        try{
            
            Connection con=DBconnection.getconnection();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM fees_details ORDER BY reciept_no DESC LIMIT 1;");
            ResultSet rs=pst.executeQuery();
            rs.next();
            txt_showreceiptno.setText(rs.getString("reciept_no"));
            txt_showmodeofpayment.setText(rs.getString("payment_mode"));
            
            String paymentmode=rs.getString("payment_mode");
            if(paymentmode.equalsIgnoreCase("cash")){
                lbl_chequedd.setText("Cheque No ");
                txt_showchequedd.setText("-");
                txt_bankname.setText(rs.getString("bank_name"));
            }
             if(paymentmode.equalsIgnoreCase("cheque")){
                lbl_chequedd.setText("Cheque No ");
                txt_showchequedd.setText(rs.getString("cheque_no"));
                txt_bankname.setText("bank_name ");
            }
             
             if(paymentmode.equalsIgnoreCase("dd")){
                lbl_chequedd.setText("DD No ");
                txt_showchequedd.setText(rs.getString("dd_no"));
                txt_bankname.setText(rs.getString("bank_name"));
            }
             if(paymentmode.equalsIgnoreCase("card ")){
                lbl_chequedd.setText("Cheque No ");
                txt_showchequedd.setText("-");
                txt_bankname.setText(rs.getString("bank_name"));
            }
             
             
            txt_showreceivedfrom.setText(rs.getString("student_name"));
            txt_showdate.setText(rs.getString("date"));
            txt_showvatamount.setText(rs.getString("vat"));
            txt_showyear1.setText(rs.getString("year1"));
            txt_showyear2.setText(rs.getString("year2"));
            txt_showinitialamount.setText(rs.getString("amount"));
            txt_showtotal.setText(rs.getString("total_amount"));
            txt_showtotalinwords.setText(rs.getString("total_in_words"));
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        panel_print = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        panelback = new javax.swing.JPanel();
        btnback = new javax.swing.JLabel();
        panelhome31 = new javax.swing.JPanel();
        btnhome31 = new javax.swing.JLabel();
        panelviewallrecord = new javax.swing.JPanel();
        btnviewallrecord = new javax.swing.JLabel();
        panelhome = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        panelhome33 = new javax.swing.JPanel();
        btnhome33 = new javax.swing.JLabel();
        panelcourselist = new javax.swing.JPanel();
        btncourselist = new javax.swing.JLabel();
        panelhome35 = new javax.swing.JPanel();
        btnhome35 = new javax.swing.JLabel();
        paneleditcourse = new javax.swing.JPanel();
        btneditcourse = new javax.swing.JLabel();
        panelhome37 = new javax.swing.JPanel();
        btnhome37 = new javax.swing.JLabel();
        panelsearchrecord = new javax.swing.JPanel();
        btnsearchrecord = new javax.swing.JLabel();
        panelhome39 = new javax.swing.JPanel();
        btnhome39 = new javax.swing.JLabel();
        panellogout1 = new javax.swing.JPanel();
        btnlogout1 = new javax.swing.JLabel();
        panel_edit = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        panel_receipt = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_showdate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txt_showchequedd = new javax.swing.JLabel();
        txt_showreceiptno = new javax.swing.JLabel();
        txt_showmodeofpayment = new javax.swing.JLabel();
        lbl_receiptno = new javax.swing.JLabel();
        lbl_modeofpayment = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        lbl_chequedd = new javax.swing.JLabel();
        txt_showreceivedfrom = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        lbl_receivedfrom = new javax.swing.JLabel();
        txt_showyear2 = new javax.swing.JLabel();
        label_followingpayment = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_showyear1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txt_showvatamount = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_signature = new javax.swing.JLabel();
        txt_showcoursename1 = new javax.swing.JLabel();
        txt_showvat1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_showinitialamount = new javax.swing.JLabel();
        txt_showtotal = new javax.swing.JLabel();
        lbl_totalinwords = new javax.swing.JLabel();
        txt_showtotalinwords = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_showtotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 51, 51));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_print.setBackground(new java.awt.Color(0, 51, 51));
        panel_print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setBackground(new java.awt.Color(255, 255, 255));
        btn_print.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btn_print.setText(" Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        panel_print.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        panelsidebar.add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 730, 330, 60));

        panelback.setBackground(new java.awt.Color(0, 51, 51));
        panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back1.png"))); // NOI18N
        btnback.setText("  Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        panelback.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 60));

        panelhome31.setBackground(new java.awt.Color(0, 51, 51));
        panelhome31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome31.setBackground(new java.awt.Color(255, 255, 255));
        btnhome31.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        btnhome31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnhome31.setText(" Home");
        btnhome31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome31MouseExited(evt);
            }
        });
        panelhome31.add(btnhome31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 40));

        panelback.add(panelhome31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 330, 60));

        panelsidebar.add(panelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 330, 60));

        panelviewallrecord.setBackground(new java.awt.Color(0, 51, 51));
        panelviewallrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelviewallrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnviewallrecord.setBackground(new java.awt.Color(255, 255, 255));
        btnviewallrecord.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btnviewallrecord.setForeground(new java.awt.Color(255, 255, 255));
        btnviewallrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnviewallrecord.setText("View All Record");
        btnviewallrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewallrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewallrecordMouseExited(evt);
            }
        });
        panelviewallrecord.add(btnviewallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 60));

        panelsidebar.add(panelviewallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 330, 60));

        panelhome.setBackground(new java.awt.Color(0, 51, 51));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setBackground(new java.awt.Color(255, 255, 255));
        btnhome.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnhome.setText(" Home");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        panelhome.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        panelhome33.setBackground(new java.awt.Color(0, 51, 51));
        panelhome33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome33.setBackground(new java.awt.Color(255, 255, 255));
        btnhome33.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        btnhome33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnhome33.setText(" Home");
        btnhome33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome33MouseExited(evt);
            }
        });
        panelhome33.add(btnhome33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 40));

        panelhome.add(panelhome33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 330, 60));

        panelsidebar.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 330, 60));

        panelcourselist.setBackground(new java.awt.Color(0, 51, 51));
        panelcourselist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelcourselist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncourselist.setBackground(new java.awt.Color(255, 255, 255));
        btncourselist.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btncourselist.setForeground(new java.awt.Color(255, 255, 255));
        btncourselist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btncourselist.setText("Course List");
        btncourselist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncourselistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncourselistMouseExited(evt);
            }
        });
        panelcourselist.add(btncourselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 60));

        panelhome35.setBackground(new java.awt.Color(0, 51, 51));
        panelhome35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome35.setBackground(new java.awt.Color(255, 255, 255));
        btnhome35.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        btnhome35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnhome35.setText(" Home");
        btnhome35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome35MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome35MouseExited(evt);
            }
        });
        panelhome35.add(btnhome35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 40));

        panelcourselist.add(panelhome35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 330, 60));

        panelsidebar.add(panelcourselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 330, 60));

        paneleditcourse.setBackground(new java.awt.Color(0, 51, 51));
        paneleditcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneleditcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btneditcourse.setBackground(new java.awt.Color(255, 255, 255));
        btneditcourse.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btneditcourse.setForeground(new java.awt.Color(255, 255, 255));
        btneditcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btneditcourse.setText("Edit Course");
        btneditcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditcourseMouseExited(evt);
            }
        });
        paneleditcourse.add(btneditcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 60));

        panelhome37.setBackground(new java.awt.Color(0, 51, 51));
        panelhome37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome37.setBackground(new java.awt.Color(255, 255, 255));
        btnhome37.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        btnhome37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnhome37.setText(" Home");
        btnhome37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome37MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome37MouseExited(evt);
            }
        });
        panelhome37.add(btnhome37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 40));

        paneleditcourse.add(panelhome37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 330, 60));

        panelsidebar.add(paneleditcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 330, 60));

        panelsearchrecord.setBackground(new java.awt.Color(0, 51, 51));
        panelsearchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelsearchrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsearchrecord.setBackground(new java.awt.Color(255, 255, 255));
        btnsearchrecord.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btnsearchrecord.setForeground(new java.awt.Color(255, 255, 255));
        btnsearchrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnsearchrecord.setText("Search Record");
        btnsearchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchrecordMouseExited(evt);
            }
        });
        panelsearchrecord.add(btnsearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 50));

        panelhome39.setBackground(new java.awt.Color(0, 51, 51));
        panelhome39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome39.setBackground(new java.awt.Color(255, 255, 255));
        btnhome39.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        btnhome39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnhome39.setText(" Home");
        btnhome39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome39MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome39MouseExited(evt);
            }
        });
        panelhome39.add(btnhome39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 40));

        panelsearchrecord.add(panelhome39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 330, 60));

        panelsidebar.add(panelsearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 330, 60));

        panellogout1.setBackground(new java.awt.Color(0, 51, 51));
        panellogout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panellogout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout1.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout1.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btnlogout1.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnlogout1.setText("Logout");
        btnlogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogout1MouseExited(evt);
            }
        });
        panellogout1.add(btnlogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 40));

        panelsidebar.add(panellogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 330, 60));

        panel_edit.setBackground(new java.awt.Color(0, 51, 51));
        panel_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setFont(new java.awt.Font("Courier New", 1, 25)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        panel_edit.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, 50));

        panelsidebar.add(panel_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 860, 330, 60));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 1000));

        panel_receipt.setBackground(new java.awt.Color(255, 255, 255));
        panel_receipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("66,Mohakhali, Dhaka 1212");
        panel_receipt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 350, 40));

        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/bracu.jpg"))); // NOI18N
        panel_receipt.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -30, 270, -1));

        txt_showdate.setBackground(new java.awt.Color(0, 0, 0));
        txt_showdate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_showdate.setForeground(new java.awt.Color(0, 0, 0));
        panel_receipt.add(txt_showdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 120, 30));
        panel_receipt.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 1150, 10));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("  Brac University");
        panel_receipt.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        txt_showchequedd.setBackground(new java.awt.Color(0, 0, 0));
        txt_showchequedd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showchequedd.setForeground(new java.awt.Color(0, 0, 0));
        panel_receipt.add(txt_showchequedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 170, 30));

        txt_showreceiptno.setBackground(new java.awt.Color(0, 0, 0));
        txt_showreceiptno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showreceiptno.setForeground(new java.awt.Color(0, 0, 0));
        panel_receipt.add(txt_showreceiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 190, 30));

        txt_showmodeofpayment.setBackground(new java.awt.Color(0, 0, 0));
        txt_showmodeofpayment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showmodeofpayment.setForeground(new java.awt.Color(0, 0, 0));
        panel_receipt.add(txt_showmodeofpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 140, 30));

        lbl_receiptno.setBackground(new java.awt.Color(0, 0, 0));
        lbl_receiptno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_receiptno.setForeground(new java.awt.Color(0, 0, 0));
        lbl_receiptno.setText("Receipt no :");
        panel_receipt.add(lbl_receiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        lbl_modeofpayment.setBackground(new java.awt.Color(0, 0, 0));
        lbl_modeofpayment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_modeofpayment.setForeground(new java.awt.Color(0, 0, 0));
        lbl_modeofpayment.setText("Mode Of Payment :");
        panel_receipt.add(lbl_modeofpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        txt_bankname.setBackground(new java.awt.Color(0, 0, 0));
        txt_bankname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_bankname.setForeground(new java.awt.Color(0, 0, 0));
        panel_receipt.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 120, 30));

        lbl_chequedd.setBackground(new java.awt.Color(0, 0, 0));
        lbl_chequedd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_chequedd.setForeground(new java.awt.Color(0, 0, 0));
        lbl_chequedd.setText("Cheque_DD :");
        panel_receipt.add(lbl_chequedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        txt_showreceivedfrom.setBackground(new java.awt.Color(0, 0, 0));
        txt_showreceivedfrom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showreceivedfrom.setForeground(new java.awt.Color(0, 0, 0));
        txt_showreceivedfrom.setText("Received from :");
        panel_receipt.add(txt_showreceivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        lbl_bankname.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bankname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_bankname.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bankname.setText("Bank name :");
        panel_receipt.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        lbl_receivedfrom.setBackground(new java.awt.Color(0, 0, 0));
        lbl_receivedfrom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_receivedfrom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_receivedfrom.setText("Received from :");
        panel_receipt.add(lbl_receivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        txt_showyear2.setBackground(new java.awt.Color(255, 255, 255));
        txt_showyear2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showyear2.setForeground(new java.awt.Color(0, 0, 0));
        txt_showyear2.setText("2021");
        panel_receipt.add(txt_showyear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, -1, -1));

        label_followingpayment.setBackground(new java.awt.Color(255, 255, 255));
        label_followingpayment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_followingpayment.setForeground(new java.awt.Color(0, 0, 0));
        label_followingpayment.setText("The following payment in the university office for the year   :");
        panel_receipt.add(label_followingpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        txt_year1.setBackground(new java.awt.Color(255, 255, 255));
        txt_year1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(0, 0, 0));
        txt_year1.setText("-");
        panel_receipt.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 20, -1));

        txt_showyear1.setBackground(new java.awt.Color(255, 255, 255));
        txt_showyear1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showyear1.setForeground(new java.awt.Color(0, 0, 0));
        txt_showyear1.setText("2021");
        panel_receipt.add(txt_showyear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Student Fees Collection Slip");
        panel_receipt.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 370, 30));

        lbl_date.setBackground(new java.awt.Color(0, 0, 0));
        lbl_date.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(0, 0, 0));
        lbl_date.setText("Date :");
        panel_receipt.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 120, 30));
        panel_receipt.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 1120, 10));
        panel_receipt.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 1120, 20));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Amount(tk)");
        panel_receipt.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, -1, -1));

        txt_showvatamount.setBackground(new java.awt.Color(255, 255, 255));
        txt_showvatamount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showvatamount.setForeground(new java.awt.Color(0, 0, 0));
        txt_showvatamount.setText("Vat");
        panel_receipt.add(txt_showvatamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 740, 100, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Head");
        panel_receipt.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Sr No :");
        panel_receipt.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("1");
        panel_receipt.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 30, -1));

        txt_signature.setBackground(new java.awt.Color(255, 255, 255));
        txt_signature.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_signature.setForeground(new java.awt.Color(0, 0, 0));
        txt_signature.setText("Receiver Signature");
        panel_receipt.add(txt_signature, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 980, 170, -1));

        txt_showcoursename1.setBackground(new java.awt.Color(255, 255, 255));
        txt_showcoursename1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showcoursename1.setForeground(new java.awt.Color(0, 0, 0));
        txt_showcoursename1.setText("1");
        panel_receipt.add(txt_showcoursename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 30, -1));

        txt_showvat1.setBackground(new java.awt.Color(255, 255, 255));
        txt_showvat1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showvat1.setForeground(new java.awt.Color(0, 0, 0));
        txt_showvat1.setText("Vat 9%");
        panel_receipt.add(txt_showvat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 740, 80, -1));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        panel_receipt.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 960, 120, 10));

        txt_showinitialamount.setBackground(new java.awt.Color(255, 255, 255));
        txt_showinitialamount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showinitialamount.setForeground(new java.awt.Color(0, 0, 0));
        txt_showinitialamount.setText("1");
        panel_receipt.add(txt_showinitialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 680, 180, 30));

        txt_showtotal.setBackground(new java.awt.Color(255, 255, 255));
        txt_showtotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showtotal.setForeground(new java.awt.Color(0, 0, 0));
        txt_showtotal.setText("Total :");
        panel_receipt.add(txt_showtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 820, 170, 40));

        lbl_totalinwords.setBackground(new java.awt.Color(255, 255, 255));
        lbl_totalinwords.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_totalinwords.setForeground(new java.awt.Color(0, 0, 0));
        lbl_totalinwords.setText("Total In Words :");
        panel_receipt.add(lbl_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 820, 150, -1));

        txt_showtotalinwords.setBackground(new java.awt.Color(255, 255, 255));
        txt_showtotalinwords.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_showtotalinwords.setForeground(new java.awt.Color(0, 0, 0));
        txt_showtotalinwords.setText("Total In Words :");
        panel_receipt.add(txt_showtotalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 810, 640, 50));
        panel_receipt.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 810, 220, 10));

        lbl_showtotal.setBackground(new java.awt.Color(255, 255, 255));
        lbl_showtotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_showtotal.setForeground(new java.awt.Color(0, 0, 0));
        lbl_showtotal.setText("Total :");
        panel_receipt.add(lbl_showtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 830, 70, -1));

        getContentPane().add(panel_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 1170, 880));

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Print Receipt");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, -1));

        setSize(new java.awt.Dimension(1898, 1171));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        Color clr=new Color(0,153,153);
        panel_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
        Color clr=new Color(0,51,51);
        panel_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        Color clr=new Color(0,153,153);
        panelback.setBackground(clr);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        Color clr=new Color(0,51,51);
        panelback.setBackground(clr);
    }//GEN-LAST:event_btnbackMouseExited

    private void btnhome31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome31MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome31MouseEntered

    private void btnhome31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome31MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome31MouseExited

    private void btnviewallrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewallrecordMouseEntered
        Color clr=new Color(0,153,153);
        panelviewallrecord.setBackground(clr);
    }//GEN-LAST:event_btnviewallrecordMouseEntered

    private void btnviewallrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewallrecordMouseExited
        Color clr=new Color(0,51,51);
        panelviewallrecord.setBackground(clr);
    }//GEN-LAST:event_btnviewallrecordMouseExited

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        Color clr=new Color(0,153,153);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        Color clr=new Color(0,51,51);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseExited

    private void btnhome33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome33MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome33MouseEntered

    private void btnhome33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome33MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome33MouseExited

    private void btncourselistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncourselistMouseEntered
        Color clr=new Color(0,153,153);
        panelcourselist.setBackground(clr);
    }//GEN-LAST:event_btncourselistMouseEntered

    private void btncourselistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncourselistMouseExited
        Color clr=new Color(0,51,51);
        panelcourselist.setBackground(clr);
    }//GEN-LAST:event_btncourselistMouseExited

    private void btnhome35MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome35MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome35MouseEntered

    private void btnhome35MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome35MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome35MouseExited

    private void btneditcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditcourseMouseEntered
        Color clr=new Color(0,153,153);
        paneleditcourse.setBackground(clr);
    }//GEN-LAST:event_btneditcourseMouseEntered

    private void btneditcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditcourseMouseExited
        Color clr=new Color(0,51,51);
        paneleditcourse.setBackground(clr);
    }//GEN-LAST:event_btneditcourseMouseExited

    private void btnhome37MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome37MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome37MouseEntered

    private void btnhome37MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome37MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome37MouseExited

    private void btnsearchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchrecordMouseEntered
        Color clr=new Color(0,153,153);
        panelsearchrecord.setBackground(clr);
    }//GEN-LAST:event_btnsearchrecordMouseEntered

    private void btnsearchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchrecordMouseExited
        Color clr=new Color(0,51,51);
        panelsearchrecord.setBackground(clr);
    }//GEN-LAST:event_btnsearchrecordMouseExited

    private void btnhome39MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome39MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome39MouseEntered

    private void btnhome39MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome39MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome39MouseExited

    private void btnlogout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1MouseEntered

    private void btnlogout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1MouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_receipt.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
}
        }
        
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        updatefeesdetails update=new  updatefeesdetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printreceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btncourselist;
    private javax.swing.JLabel btneditcourse;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnhome31;
    private javax.swing.JLabel btnhome33;
    private javax.swing.JLabel btnhome35;
    private javax.swing.JLabel btnhome37;
    private javax.swing.JLabel btnhome39;
    private javax.swing.JLabel btnlogout1;
    private javax.swing.JLabel btnsearchrecord;
    private javax.swing.JLabel btnviewallrecord;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label_followingpayment;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_chequedd;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_modeofpayment;
    private javax.swing.JLabel lbl_receiptno;
    private javax.swing.JLabel lbl_receivedfrom;
    private javax.swing.JLabel lbl_showtotal;
    private javax.swing.JLabel lbl_totalinwords;
    private javax.swing.JPanel panel_edit;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panel_receipt;
    private javax.swing.JPanel panelback;
    private javax.swing.JPanel panelcourselist;
    private javax.swing.JPanel paneleditcourse;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelhome31;
    private javax.swing.JPanel panelhome33;
    private javax.swing.JPanel panelhome35;
    private javax.swing.JPanel panelhome37;
    private javax.swing.JPanel panelhome39;
    private javax.swing.JPanel panellogout1;
    private javax.swing.JPanel panelsearchrecord;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JPanel panelviewallrecord;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_showchequedd;
    private javax.swing.JLabel txt_showcoursename1;
    private javax.swing.JLabel txt_showdate;
    private javax.swing.JLabel txt_showinitialamount;
    private javax.swing.JLabel txt_showmodeofpayment;
    private javax.swing.JLabel txt_showreceiptno;
    private javax.swing.JLabel txt_showreceivedfrom;
    private javax.swing.JLabel txt_showtotal;
    private javax.swing.JLabel txt_showtotalinwords;
    private javax.swing.JLabel txt_showvat1;
    private javax.swing.JLabel txt_showvatamount;
    private javax.swing.JLabel txt_showyear1;
    private javax.swing.JLabel txt_showyear2;
    private javax.swing.JLabel txt_signature;
    private javax.swing.JLabel txt_year1;
    // End of variables declaration//GEN-END:variables
}
